hostname arista-switch-ztp
!
ntp server 1.1.1.1
ntp server 8.8.8.8
!
username admin privilege 15 secret Arista123!
!
vlan 1
   name default
!
interface Management1
   ip address dhcp
!
interface Ethernet1
   switchport mode access
   switchport access vlan 1
!
interface Ethernet2
   switchport mode access
   switchport access vlan 1
!
ip routing
ip route 0.0.0.0/0 192.168.2.254
!
management api http-commands
   no shutdown
!
