hostname arista-router-ztp
!
ntp server 1.1.1.1
ntp server 8.8.8.8
!
username admin privilege 15 secret Arista123!
!
interface Management1
   ip address dhcp
!
ip routing
ip route 0.0.0.0/0 192.168.2.254
!
management api http-commands
   no shutdown
!
